let darkTheme=false;try{darkTheme=localStorage.getItem('solid-lab-theme')==='dark'}catch{}document.documentElement.dataset.theme=darkTheme?'dark':'light';
const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>Math.hypot(...a),unit=a=>a.map(v=>v/norm(a));
function hull(v){let found=new Map();for(let i=0;i<v.length;i++)for(let j=i+1;j<v.length;j++)for(let k=j+1;k<v.length;k++){let n=cross(sub(v[j],v[i]),sub(v[k],v[i]));if(norm(n)<1e-7)continue;n=unit(n);let d=v.map(p=>dot(n,sub(p,v[i])));if(d.some(x=>x>1e-6)&&d.some(x=>x< -1e-6))continue;let ids=d.map((x,a)=>Math.abs(x)<1e-6?a:-1).filter(x=>x>=0),key=ids.join(',');if(found.has(key))continue;let c=[0,1,2].map(a=>ids.reduce((s,b)=>s+v[b][a],0)/ids.length);if(dot(n,c)<0)n=n.map(x=>-x);let u=unit(sub(v[ids[0]],c)),w=cross(n,u);ids.sort((a,b)=>Math.atan2(dot(sub(v[a],c),w),dot(sub(v[a],c),u))-Math.atan2(dot(sub(v[b],c),w),dot(sub(v[b],c),u)));found.set(key,ids)}let f=[...found.values()].sort((a,b)=>a.length-b.length),em=new Map();f.forEach(face=>face.forEach((a,i)=>{let b=face[(i+1)%face.length],key=[a,b].sort((x,y)=>x-y).join(',');em.set(key,[a,b])}));return{v,f,e:[...em.values()]}}
let p=[],h=Math.sqrt(Math.SQRT2)/2;for(let z of [-1,1])for(let i=0;i<4;i++){let a=i*Math.PI/2+(z===1?Math.PI/4:0);p.push([Math.cos(a),Math.sin(a),z*h])}p.push([0,0,h+1],[0,0,-h-1]);let a=hull(p);p=[];for(let zero=0;zero<3;zero++)for(let x of [-1,1])for(let y of [-1,1]){let q=[x,y];q.splice(zero,0,0);p.push(q)}let b=hull(p);p=[];const phi=(1+Math.sqrt(5))/2;for(let x of [-1,1])for(let y of [-phi,phi])p.push([0,x,y],[x,y,0],[y,0,x]);let ico=hull(p),cut=[];ico.e.forEach(([i,j])=>{cut.push(p[i].map((x,k)=>(2*x+p[j][k])/3),p[j].map((x,k)=>(2*x+p[i][k])/3))});let c=hull(cut);const models=[a,b,c];
const data=[{title:'正三角形の十六面体',legend:[['正三角形','#6495ed']],foot:'正三角形の十六面体は画像に合わせた形。頂点に集まる面の数が同じではないから、全部を同じ数で割らないのがコツだぞ。',lessons:[['三角形の面は、全部で16枚','「十六面体」は、面が16枚ある立体のことだぞ。上の山に4枚、真ん中の帯に8枚、下の山に4枚ある。','4 ＋ 8 ＋ 4 ＝ 16 面','色を増やして、回しながら16枚の三角形を確かめよう。'],['辺は、2つの面の共有物','三角形1枚には辺が3本。16枚分で48本分になる。でも、同じ辺を両側の面で2回ずつ数えているぞ。','16 × 3 ÷ 2 ＝ 24 本','どの辺も2枚の面にはさまれている。だから2で割るんだ。'],['頂点は、段ごとに数えよう','上の先に1個、上の輪に4個、下の輪に4個、下の先に1個。合わせればいいぞ。','1 ＋ 4 ＋ 4 ＋ 1 ＝ 10 個','公式でも確認：頂点 ＝ 辺 − 面 ＋ 2 ＝ 24 − 16 ＋ 2 ＝ 10。']]},{title:'立方体の頂点を切った立体',legend:[['切り口の三角形','#f1aa44'],['元の面から残る正方形','#6495ed']],foot:'正六面体を切った立体は画像のように、切り口が元の辺の真ん中で接する切り方（立方八面体）。浅く切る場合とは面の形や頂点の数が変わるぞ。',lessons:[['切り口8枚 ＋ 元の面6枚','立方体の8つの頂点を切ると、三角形の切り口が8枚できる。元の6枚の面は、小さな正方形になって残るぞ。','8 ＋ 6 ＝ 14 面','オレンジが新しい切り口、青が元の面から残った部分だ。'],['2種類の面の辺を足そう','三角形8枚には24本分、正方形6枚にも24本分の辺がある。合計では、各辺を2回ずつ数えているぞ。','（8 × 3 ＋ 6 × 4）÷ 2 ＝ 24 本','別の考え方：各辺には三角形がちょうど1枚つくので、8 × 3 ＝ 24でも求められる。'],['元の辺の真ん中が頂点になる','切った後の頂点は、元の立方体の辺の真ん中に1個ずつできる。立方体の辺は12本だぞ。','12 × 1 ＝ 12 個','1つの頂点には三角形2枚と正方形2枚が集まる。面の角から数えても（8 × 3 ＋ 6 × 4）÷ 4 ＝ 12。']]},{title:'正二十面体の頂点を切った立体',legend:[['切り口の五角形','#f1aa44'],['元の面から残る六角形','#6495ed']],foot:'正二十面体を切った立体の元の正二十面体は、面20枚・辺30本・頂点12個。各頂点に正三角形が5枚集まるぞ。図はサッカーボールと同じ面の組合せだ。',lessons:[['五角形12枚 ＋ 六角形20枚','元の12個の頂点を切ると、五角形が12枚できる。元の三角形20枚は、3つの角が切られて六角形になるぞ。','12 ＋ 20 ＝ 32 面','元の頂点の数：20 × 3 ÷ 5 ＝ 12。五角形は切り口、六角形は元の面の残りだ。'],['面の辺を合計して、2で割る','五角形12枚で60本分。六角形20枚で120本分。両方を足すと、どの辺も2回ずつ数えているぞ。','（12 × 5 ＋ 20 × 6）÷ 2 ＝ 90 本','五角形につく辺だけでは足りない。六角形どうしの境目の辺も忘れないで数えよう。'],['1つの頂点に、3枚の面','どの頂点にも五角形1枚と六角形2枚が集まる。面の角を全部足すと、同じ頂点を3回ずつ数えるぞ。','（12 × 5 ＋ 20 × 6）÷ 3 ＝ 60 個','別の考え方：元の30本の辺に、新しい頂点が2個ずつできるから、30 × 2 ＝ 60。']]}];

const cubeVertices=[];for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])cubeVertices.push([x,y,z]);
models.push(hull([[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]]),hull(cubeVertices),hull([[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]),hull(ico.f.map(face=>[0,1,2].map(k=>face.reduce((sum,id)=>sum+ico.v[id][k],0)/face.length))),ico);
const regularSolids=[
{title:'正四面体',face:'正三角形',sides:3,F:4,E:6,V:4,meet:3,detail:'底の三角形が1枚、まわりの三角形が3枚あるぞ。',sum:'1 ＋ 3 ＝ 4 面'},
{title:'正六面体（立方体）',face:'正方形',sides:4,F:6,E:12,V:8,meet:3,detail:'上と下に2枚、まわりに4枚の正方形があるぞ。',sum:'2 ＋ 4 ＝ 6 面'},
{title:'正八面体',face:'正三角形',sides:3,F:8,E:12,V:6,meet:4,detail:'上下の四角すいが底どうしでくっついた形だ。外側には上に4枚、下に4枚の三角形があるぞ。',sum:'4 ＋ 4 ＝ 8 面'},
{title:'正十二面体',face:'正五角形',sides:5,F:12,E:30,V:20,meet:3,detail:'1枚の面のまわりに5枚。その反対側にも同じように1枚と5枚あるぞ。',sum:'1 ＋ 5 ＋ 5 ＋ 1 ＝ 12 面'},
{title:'正二十面体',face:'正三角形',sides:3,F:20,E:30,V:12,meet:5,detail:'1つの頂点のまわりに5枚。反対側の頂点のまわりにも5枚。その間の帯に10枚あるぞ。',sum:'5 ＋ 10 ＋ 5 ＝ 20 面'}
];
regularSolids.forEach(s=>data.push({title:s.title,legend:[[s.face,'#6495ed']],foot:s.title+'は、どの面も同じ'+s.face+'で、どの頂点にも'+s.meet+'枚の面が集まる正多面体だぞ。',lessons:[
[s.face+'が'+s.F+'枚',s.detail,s.sum,'「面をはがして並べる」で、裏側の面も全部取り出して数えてみよう。'],
['面の辺を足して、2で割る',s.face+'1枚の辺は'+s.sides+'本。'+s.F+'枚分の辺を足すと、同じ辺を隣り合う2枚の面で2回ずつ数えるぞ。',s.F+' × '+s.sides+' ÷ 2 ＝ '+s.E+' 本','立体に戻すと、切り離した2本の辺が1本の境目になる。だから2で割るんだ。'],
['1つの頂点に'+s.meet+'枚の面',s.face+'1枚には角が'+s.sides+'個。全部の面の角を足すと、同じ頂点を'+s.meet+'回ずつ数えるぞ。',s.F+' × '+s.sides+' ÷ '+s.meet+' ＝ '+s.V+' 個','公式でも確認：頂点 '+s.V+' − 辺 '+s.E+' ＋ 面 '+s.F+' ＝ 2。']]}));

// Rigid hinge unfolding. Each face retains its shape and every tree edge stays joined.
const NetEngine=(()=>{
const add=(a,b)=>a.map((x,i)=>x+b[i]),sub=(a,b)=>a.map((x,i)=>x-b[i]),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>a.map(x=>x/Math.hypot(...a));
const identity=()=>[[1,0,0],[0,1,0],[0,0,1]],mv=(m,v)=>m.map(r=>dot(r,v)),mm=(a,b)=>a.map(r=>[0,1,2].map(k=>r.reduce((s,x,j)=>s+x*b[j][k],0)));
function rot(u,t){const [x,y,z]=u,c=Math.cos(t),s=Math.sin(t),d=1-c;return [[c+x*x*d,x*y*d-z*s,x*z*d+y*s],[y*x*d+z*s,c+y*y*d,y*z*d-x*s],[z*x*d-y*s,z*y*d+x*s,c+z*z*d]]}
function normal(m,i){const f=m.f[i];return unit(cross(sub(m.v[f[1]],m.v[f[0]]),sub(m.v[f[2]],m.v[f[0]])))}
function adjacency(m){return m.f.map((f,i)=>m.f.map((g,j)=>j!==i&&f.filter(x=>g.includes(x)).length===2?j:-1).filter(j=>j>=0))}
function rootTree(edges,root,count){const parents=Array(count).fill(-2),order=[root];parents[root]=-1;for(let k=0;k<order.length;k++)for(const [a,b]of edges){let n=a===order[k]?b:b===order[k]?a:-1;if(n>=0&&parents[n]===-2){parents[n]=order[k];order.push(n)}}return{parents,order}}
function unfold(m,edges,root,u){const {parents,order}=rootTree(edges,root,m.f.length),transforms=Array(m.f.length);transforms[root]={r:identity(),t:[0,0,0]};for(const child of order.slice(1)){const parent=parents[child],shared=m.f[parent].filter(v=>m.f[child].includes(v)),a=m.v[shared[0]],axis=unit(sub(m.v[shared[1]],a)),np=normal(m,parent),nc=normal(m,child),angle=Math.atan2(dot(axis,cross(nc,np)),dot(nc,np)),r=rot(axis,angle*u),t=sub(a,mv(r,a)),p=transforms[parent];transforms[child]={r:mm(p.r,r),t:add(mv(p.r,t),p.t)}}const n=normal(m,root),origin=m.v[m.f[root][0]],x=unit(sub(m.v[m.f[root][1]],origin)),y=cross(n,x);return m.f.map((f,i)=>f.map(id=>{const t=transforms[i],q=sub(add(mv(t.r,m.v[id]),t.t),origin);return[dot(q,x),dot(q,y),-dot(q,n)]}))}
function overlap(a,b){for(const poly of [a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],axis=[p[1]-q[1],q[0]-p[0]];let aa=a.map(v=>v[0]*axis[0]+v[1]*axis[1]),bb=b.map(v=>v[0]*axis[0]+v[1]*axis[1]);if(Math.min(...aa)>=Math.max(...bb)-1e-7||Math.min(...bb)>=Math.max(...aa)-1e-7)return false}return true}
function score(polys){let collisions=0;for(let i=0;i<polys.length;i++)for(let j=i+1;j<polys.length;j++)if(overlap(polys[i],polys[j]))collisions++;const pts=polys.flat(),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);return{collisions,area:(Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys))}}
function findTree(m){const adj=adjacency(m);let best=null,seed=91;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};for(let attempt=0;attempt<1800;attempt++){let seen=new Set([0]),edges=[];while(seen.size<m.f.length){const frontier=[];for(const a of seen)for(const b of adj[a])if(!seen.has(b))frontier.push([a,b]);const edge=frontier[Math.floor(rand()*frontier.length)];edges.push(edge);seen.add(edge[1])}const s=score(unfold(m,edges,0,1));if(s.collisions===0&&(!best||s.area<best.area))best={edges,area:s.area};if(best&&attempt>120)break}if(!best)throw Error('No non-overlapping net');return best.edges}
return{unfold,adjacency,findTree,score,normal,rootTree};})();




const supplied=hull([[1,0,0],[0,.5,0],[0,0,.5],[0,0,0]].map(p=>p.map((v,i)=>v-[.25,.125,.125][i])));
supplied.f=[[0,1,2],[0,1,3],[1,2,3],[0,2,3]].map(ids=>supplied.f.find(face=>ids.every(id=>face.includes(id))));models.push(supplied);
data.push({title:'画像の展開図から作る三角すい',legend:[['三角形（形は3種類）','#6495ed']],foot:'画像の外枠ABCDを正方形、E・Fを辺の中点として再現。点線AE・EF・FAで折り、B・C・Dを重ねて頂点Oにする。左側の破線は面として扱わない。',lessons:[['形の違う三角形が4枚','中央のAEFと、そのまわりのABE・ECF・ADFの4枚を折り合わせるぞ。どの面を底面に選んでも同じ三角すいになる。','1 ＋ 3 ＝ 4 面','AEFとECFは二等辺三角形。ABEとADFは合同な直角三角形。ECFも直角三角形だぞ。'],['2枚の面が1本の辺を共有','三角形4枚の辺を足すと12本分。組み立てると同じ辺を2回ずつ数えているぞ。','4 × 3 ÷ 2 ＝ 6 本','完成した立体の辺はAE・AF・EF・AO・EO・FOだ。'],['B・C・Dが1つに重なる','展開図ではA・B・C・D・E・Fの6点。組み立てるとB・C・Dが1つの頂点Oになるぞ。','6 − 2 ＝ 4 個','完成した頂点はA・E・F・O。底面AEFならOが上の頂点になる。']]});
const netTrees={"3":[[0,3],[3,2],[2,1]],"4":[[0,1],[0,2],[1,5],[2,4],[4,3]],"5":[[0,4],[4,5],[5,1],[5,7],[4,6],[7,3],[3,2]],"6":[[0,1],[1,2],[0,5],[0,3],[5,9],[9,11],[1,6],[0,4],[6,10],[6,7],[6,8]],"7":[[0,5],[5,9],[9,14],[0,1],[14,11],[14,15],[0,2],[5,7],[1,4],[4,17],[15,19],[17,10],[17,18],[2,3],[7,6],[19,12],[9,8],[15,13],[18,16]]};netTrees[8]=[[0,1],[0,2],[0,3]];
let netState=null,netAnimation=null,netRoot=0,netYaw=0,netPitch=0;


const cutConfigs={
1:{source:4,name:'立方体',cap:3,capName:'三角形',oldName:'正方形',originalName:'正方形',oldSides:4,t:.5,cutCount:8,oldCount:6,mark:'元の辺の真ん中に印をつける。',tip:'浅く切ると元の面は八角形。辺の真ん中まで切ると正方形になるぞ。'},
2:{source:7,name:'正二十面体',cap:5,capName:'五角形',oldName:'六角形',originalName:'正三角形',oldSides:6,t:1/3,cutCount:12,oldCount:20,mark:'元の辺を3等分して、それぞれの頂点から3分の1の位置に印をつける。',tip:'元の三角形の3つの角を切ると六角形になる。完成位置で辺の長さがそろうぞ。'},
9:{source:3,name:'正四面体',cap:3,capName:'三角形',oldName:'六角形',originalName:'正三角形',oldSides:6,t:1/3,cutCount:4,oldCount:4,mark:'元の辺を3等分して、それぞれの頂点から3分の1の位置に印をつける。',tip:'4つの頂点に三角形ができ、元の三角形4枚は六角形になるぞ。'},
10:{source:5,name:'正八面体',cap:4,capName:'正方形',oldName:'六角形',originalName:'正三角形',oldSides:6,t:1/3,cutCount:6,oldCount:8,mark:'元の辺を3等分して、それぞれの頂点から3分の1の位置に印をつける。',tip:'各頂点に4枚の面が集まるので、切り口は正方形。元の三角形8枚は六角形になるぞ。'},
11:{source:6,name:'正十二面体',cap:3,capName:'三角形',oldName:'十角形',originalName:'正五角形',oldSides:10,t:1/(2+2*Math.cos(Math.PI/5)),cutCount:20,oldCount:12,mark:'辺の両端から同じ割合で印をつける。完成位置は辺の長さの約27.6％で、切り口の辺と元の辺の残りが同じ長さになる位置だ。',tip:'五角形の5つの角を切ると、辺が5本増えて十角形になる。3等分で切る位置とは違うぞ。'}
};
function buildTruncationHull(source,t,cap){const verts=[],seen=new Set();source.e.forEach(([a,b])=>{for(const [from,to]of [[a,b],[b,a]]){const p=source.v[from].map((v,k)=>v*(1-t)+source.v[to][k]*t),key=p.map(v=>v.toFixed(9)).join(',');if(!seen.has(key)){seen.add(key);verts.push(p)}}});const model=hull(verts);model.newFaces=new Set(model.f.map((f,i)=>{const n=unit(cross(sub(model.v[f[1]],model.v[f[0]]),sub(model.v[f[2]],model.v[f[0]])));return source.v.some(v=>dot(unit(v),n)>1-1e-6)?i:-1}).filter(i=>i>=0));return model}

// Connectivity stays fixed between the original and touching endpoints.
// Reuse it and move only the directed-edge vertices while dragging.
const truncationCache=new WeakMap();
function truncateSource(source,t,cap){let cache=truncationCache.get(source);if(!cache){cache={};truncationCache.set(source,cache)}if(t>=.5){if(!cache.touch)cache.touch=buildTruncationHull(source,.5,cap);return cache.touch}if(!cache.topology)cache.topology=buildTruncationHull(source,.25,cap);const v=[];for(const [a,b]of source.e){v.push(source.v[a].map((x,k)=>x+(source.v[b][k]-x)*t),source.v[b].map((x,k)=>x+(source.v[a][k]-x)*t))}return {v,f:cache.topology.f,e:cache.topology.e,newFaces:cache.topology.newFaces}}

for(const id of [9,10,11]){const c=cutConfigs[id],source=models[c.source],model=truncateSource(source,c.t,c.cap);models.push(model);data.push({title:c.name+'の頂点を切った立体',legend:[['切り口の'+c.capName,'#f1aa44'],['元の面から残る'+c.oldName,'#6495ed']],foot:c.name+'の'+source.v.length+'個の頂点を同じ深さで切った形。完成形は2種類の正多角形からできているぞ。',lessons:[
['切り口'+c.cutCount+'枚 ＋ 元の面'+c.oldCount+'枚',c.name+'の'+c.cutCount+'個の頂点に'+c.capName+'の切り口ができる。元の'+c.oldCount+'枚の'+c.originalName+'は'+c.oldName+'になって残るぞ。',c.cutCount+' ＋ '+c.oldCount+' ＝ '+model.f.length+' 面','オレンジが切り口、青が元の面から残った部分。「作り方を見る」で途中の変化を確かめよう。'],
['面の辺を足して、2で割る',c.capName+c.cutCount+'枚と'+c.oldName+c.oldCount+'枚の辺を全部足す。同じ辺を2枚の面で数えているから、2で割るぞ。','（'+c.cutCount+' × '+c.cap+' ＋ '+c.oldCount+' × '+c.oldSides+'）÷ 2 ＝ '+model.e.length+' 本','切り口どうしは接しない。元の面から残った面どうしの境目も忘れずに数えよう。'],
['元の辺1本に、新しい頂点が2個',c.name+'の辺は'+source.e.length+'本。辺の両端側で切り取るので、それぞれの辺に新しい頂点が2個できるぞ。',source.e.length+' × 2 ＝ '+model.v.length+' 個','完成した1つの頂点には3枚の面が集まる。面の角の合計を3で割っても求められるぞ。']]})}

let cutProgress=1,cutModel=null;
let separation=0,peelAnimation=null;
let selected=8,mode=0,amount=4,rx=-.25,ry=.4,auto=false,ghost=false;const $=id=>document.getElementById(id),cv=$('view'),ctx=cv.getContext('2d');const labels=['面','辺','頂点'];
function update(){$('count').disabled=!!cutModel;const d=data[selected],m=models[selected],l=d.lessons[mode],total=[m.f.length,m.e.length,m.v.length][mode];amount=Math.min(amount,total);$('shapeTitle').textContent=d.title;$('stepLabel').textContent=`STEP ${mode+1} · ${labels[mode]}を数える`;$('lessonTitle').textContent=l[0];$('explain').textContent=l[1];$('formula').textContent=l[2];$('note').textContent=l[3];$('footnote').textContent=d.foot;$('legend').innerHTML=d.legend.map(([s,col])=>`<span><i class="dot" style="background:${col}"></i>${s}</span>`).join('');$('count').max=total;$('count').value=amount;$('counter').textContent=`${amount} ／ ${total}`;$('summary').setAttribute('aria-label',cutModel?'完成後の面・辺・頂点の数':'面・辺・頂点の数');$('summary').title=cutModel?'完成後の数':'';$('summary').innerHTML=[m.f.length,m.e.length,m.v.length].map((n,i)=>`<div class="stat"><span>${cutModel?'完成後の':''}${labels[i]}</span><strong>${n}</strong></div>`).join('');$('euler').textContent=`答えの確認：頂点 ${m.v.length} − 辺 ${m.e.length} ＋ 面 ${m.f.length} ＝ 2`;document.querySelectorAll('[data-solid]').forEach(el=>{el.classList.toggle('active',+el.dataset.solid===selected);el.setAttribute('aria-pressed',+el.dataset.solid===selected)});document.querySelectorAll('[data-mode]').forEach(el=>{el.classList.toggle('active',+el.dataset.mode===mode);el.setAttribute('aria-pressed',+el.dataset.mode===mode)});syncPeel();syncNet();draw()}
function changeMode(n){netState=null;netAnimation=null;if(cutModel){cutProgress=1;cutModel=null;syncBuildGuide()}if((n+3)%3!==0){separation=0;peelAnimation=null;syncPeel()}mode=(n+3)%3;amount=[models[selected].f.length,models[selected].e.length,models[selected].v.length][mode];update()}
document.querySelectorAll('[data-solid]').forEach(el=>el.onclick=()=>{selected=+el.dataset.solid;cutProgress=1;cutModel=null;syncBuildGuide();rx=-.25;ry=.4;changeMode(0);resetNetForSelection();update()});document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>changeMode(+el.dataset.mode));$('next').onclick=()=>changeMode(mode+1);$('prev').onclick=()=>changeMode(mode-1);$('count').oninput=e=>{amount=+e.target.value;update()};$('reset').onclick=()=>{netYaw=0;netPitch=0;rx=-.25;ry=.4;draw()};$('rotate').onclick=()=>{auto=!auto;$('rotate').textContent=auto?'回転を止める':'自動で回す';$('rotate').setAttribute('aria-pressed',auto)};$('ghost').onclick=()=>{ghost=!ghost;$('ghost').classList.toggle('active',ghost);$('ghost').setAttribute('aria-pressed',ghost);draw()};
function draw(){let w=cv.clientWidth,h=cv.clientHeight,dpr=window.devicePixelRatio||1;if(cv.width!==w*dpr||cv.height!==h*dpr){cv.width=w*dpr;cv.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(netState!==null){drawNet(w,h);return}if(separation>0){drawSeparated(w,h);return}let m=cutModel||models[selected],radius=Math.max(...m.v.map(norm)),scale=Math.min(w*.46,h*.46)/radius;let pts=m.v.map(([x,y,z])=>{[y,z]=[y*Math.cos(rx)-z*Math.sin(rx),y*Math.sin(rx)+z*Math.cos(rx)];[x,z]=[x*Math.cos(ry)+z*Math.sin(ry),-x*Math.sin(ry)+z*Math.cos(ry)];return[x*scale+w/2,-y*scale+h/2,z]});let faces=m.f.map((ids,i)=>({ids,i,z:ids.reduce((s,k)=>s+pts[k][2],0)/ids.length,front:cross(sub(pts[ids[1]],pts[ids[0]]),sub(pts[ids[2]],pts[ids[0]]))[2]<0})).sort((a,b)=>a.z-b.z);let visible=new Set(),vedge=new Set();faces.filter(f=>f.front).forEach(f=>f.ids.forEach((a,i)=>{visible.add(a);vedge.add([a,f.ids[(i+1)%f.ids.length]].sort((x,y)=>x-y).join(','))}));faces.forEach(f=>{if(!f.front)return;ctx.beginPath();f.ids.forEach((k,i)=>i?ctx.lineTo(...pts[k].slice(0,2)):ctx.moveTo(...pts[k].slice(0,2)));ctx.closePath();let orange=cutModel?!!cutModel.newFaces?.has(f.i):!!cutConfigs[selected]&&f.ids.length===cutConfigs[selected].cap;ctx.fillStyle=mode===0&&(cutModel||f.i<amount)?(orange?'#f3b557':'#80a6ed'):(darkTheme?'#344862':'#edf1f7');ctx.fill();ctx.strokeStyle=(darkTheme?'#b1c5e0':'#546b8b');ctx.lineWidth=1.5;ctx.stroke()});m.e.forEach(([a,b],i)=>{let seen=vedge.has([a,b].sort((x,y)=>x-y).join(','));if(!seen&&!ghost)return;ctx.beginPath();ctx.moveTo(...pts[a].slice(0,2));ctx.lineTo(...pts[b].slice(0,2));ctx.setLineDash(seen?[]:[4,5]);ctx.strokeStyle=mode===1&&i<amount?(seen?'#eb781b':'#c48b60'):(seen?(darkTheme?'#b1c5e0':'#405e87'):'#aebaca');ctx.lineWidth=mode===1&&i<amount?4:1.4;ctx.stroke();ctx.setLineDash([])});if(mode===2)pts.forEach(([x,y],i)=>{let seen=visible.has(i);if(!seen&&!ghost)return;ctx.beginPath();ctx.arc(x,y,i<amount?6:3,0,2*Math.PI);ctx.fillStyle=i<amount?(seen?'#d23d70':'#e99ab5'):'#b6c1d2';ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=1.5;ctx.stroke()})}
let drag=null;cv.onpointerdown=e=>{drag=[e.clientX,e.clientY];cv.setPointerCapture(e.pointerId)};cv.onpointermove=e=>{if(!drag||separation>0)return;if(netState!==null){netYaw+=(e.clientX-drag[0])*.008;netPitch+=(e.clientY-drag[1])*.008;drag=[e.clientX,e.clientY];draw();return}ry+=(e.clientX-drag[0])*.009;rx+=(e.clientY-drag[1])*.009;drag=[e.clientX,e.clientY];draw()};cv.onpointerup=cv.onpointercancel=()=>drag=null;cv.onkeydown=e=>{if(separation>0)return;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(netState!==null){netYaw+=e.key==='ArrowRight'?.15:e.key==='ArrowLeft'?-.15:0;netPitch+=e.key==='ArrowDown'?.15:e.key==='ArrowUp'?-.15:0;draw();return}ry+=e.key==='ArrowRight'?.15:e.key==='ArrowLeft'?-.15:0;rx+=e.key==='ArrowDown'?.15:e.key==='ArrowUp'?-.15:0;draw()};$('peelAll').onclick=()=>animatePeel(1);$('assemble').onclick=()=>animatePeel(0);$('peel').oninput=e=>{netState=null;netAnimation=null;if(cutModel){cutProgress=1;cutModel=null;syncBuildGuide()}peelAnimation=null;separation=+e.target.value/100;if(mode!==0){mode=0;amount=models[selected].f.length}update()};
new ResizeObserver(draw).observe(cv);let last=0;function tick(t){tickNet(t);if(peelAnimation){let u=Math.min(1,(t-peelAnimation.start)/1000);let ease=u*u*(3-2*u);separation=peelAnimation.from+(peelAnimation.to-peelAnimation.from)*ease;if(u===1)peelAnimation=null;syncPeel();draw()}if(auto&&!drag&&separation===0&&!peelAnimation){ry+=Math.min(t-last,40)*.0003;draw()}last=t;requestAnimationFrame(tick)}update();requestAnimationFrame(tick);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_solid_lesson',description:'立体と説明を選択。solidは1:正四面体、2:正六面体、3:正八面体、4:正十二面体、5:正二十面体、6:十六面体、7:立方体を切った形、8:正二十面体を切った形、9:画像の三角すい、10:正四面体を切る、11:正八面体を切る、12:正十二面体を切る。modeは0:面、1:辺、2:頂点。',inputSchema:{type:'object',properties:{solid:{type:'integer',minimum:1,maximum:12},mode:{type:'integer',minimum:0,maximum:2}},required:['solid','mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!Number.isInteger(input.solid)||input.solid<1||input.solid>12||!Number.isInteger(input.mode)||input.mode<0||input.mode>2)throw Error('選択が範囲外です');selected=[3,4,5,6,7,0,1,2,8,9,10,11][input.solid-1];cutProgress=1;cutModel=null;syncBuildGuide();changeMode(input.mode);return{solid:input.solid,mode:labels[mode],explanation:data[selected].lessons[mode]}}})).catch(()=>{})}catch{}}

const polygonNames={3:'三角形',4:'四角形（正方形）',5:'五角形',6:'六角形',10:'十角形'};

function faceGroups(){const names={3:'三角形',4:'四角形（正方形）',5:'五角形',6:'六角形',10:'十角形'};let groups=[];models[selected].f.forEach((f,i)=>{let g=groups.find(g=>g.sides===f.length);if(!g){g={sides:f.length,name:names[f.length],ids:[]};groups.push(g)}g.ids.push(i)});return groups}
function faceColor(sides){return (cutConfigs[selected]&&sides===cutConfigs[selected].cap)?'#f3b557':'#80a6ed'}
function syncPeel(){const groups=faceGroups();$('peel').value=Math.round(separation*100);$('peelStatus').textContent=separation===0?'「面をはがして並べる」を押すと、裏側の面も全部取り出せるぞ。':separation<1?'面を切り離しているぞ。つまみを右へ動かすと、形ごとに平らに並ぶ。':groups.map(g=>g.name+'が'+g.ids.length+'枚').join('、')+'。全部で'+models[selected].f.length+'枚だ！';$('faceTotals').innerHTML=groups.map(g=>'<span><i class="dot" style="background:'+faceColor(g.sides)+'"></i>'+g.name+' <b>'+g.ids.length+'枚</b></span>').join('');$('viewHint').textContent=separation===0?'裏側も回して見てみよう。矢印キーでも回せるぞ。':'同じ形をまとめて並べるぞ。面の番号で1枚ずつ数えよう。';$('rotate').disabled=separation>0;$('reset').disabled=separation>0;$('ghost').disabled=separation>0;$('assemble').disabled=separation===0&&!peelAnimation;$('peelAll').disabled=separation===1&&!peelAnimation;cv.style.cursor=separation>0?'default':'grab';cv.setAttribute('aria-label',separation===0?'立体。ドラッグまたは矢印キーで回転できます':'切り離した面。'+groups.map(g=>g.name+g.ids.length+'枚').join('、'))}
function animatePeel(to){netState=null;netAnimation=null;if(cutModel){cutProgress=1;cutModel=null;syncBuildGuide()}if(to>0){mode=0;amount=models[selected].f.length}if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){separation=to;peelAnimation=null}else{peelAnimation={from:separation,to,start:performance.now()}}update()}
function drawSeparated(w,h){const m=models[selected],groups=faceGroups(),radius=Math.max(...m.v.map(norm)),scale=Math.min(w*.46,h*.46)/radius;const project=([x,y,z])=>{[y,z]=[y*Math.cos(rx)-z*Math.sin(rx),y*Math.sin(rx)+z*Math.cos(rx)];[x,z]=[x*Math.cos(ry)+z*Math.sin(ry),-x*Math.sin(ry)+z*Math.cos(ry)];return [x*scale+w/2,-y*scale+h/2,z]};const gridT=Math.max(0,(separation-.22)/.78),blend=gridT*gridT*(3-2*gridT);let layouts=[],offset=16;const groupH=(h-24)/groups.length;
groups.forEach(g=>{const cols=Math.min(5,Math.max(3,Math.floor((w-32)/64))),rows=Math.ceil(g.ids.length/cols),cellW=(w-32)/cols,cellH=(groupH-34)/rows,r=Math.min(cellW*.34,cellH*.37);layouts.push({g,cols,cellW,cellH,r,y:offset});offset+=groupH});
let polys=[];layouts.forEach(layout=>{const {g,cols,cellW,cellH,r,y}=layout;g.ids.forEach((fi,j)=>{let face=m.f[fi],center=[0,1,2].map(k=>face.reduce((s,id)=>s+m.v[id][k],0)/face.length),normal=unit(center),cx=16+cellW*(j%cols+.5),cy=y+30+cellH*(Math.floor(j/cols)+.5);let local=null,lc=null,lr=1;if(selected===8){local=NetEngine.unfold(m,netTrees[8],fi,1)[fi];lc=[0,1].map(n=>local.reduce((s,p)=>s+p[n],0)/local.length);lr=Math.max(...local.map(p=>Math.hypot(p[0]-lc[0],p[1]-lc[1])))}let points=face.map((id,k)=>{let expanded=m.v[id].map((x,n)=>(x+normal[n]*radius*.25*Math.min(1,separation/.22))/(1+.25*Math.min(1,separation/.22))),origin=project(expanded),angle=-Math.PI/2+2*Math.PI*k/face.length;return[origin[0]*(1-blend)+(cx+(local?(local[k][0]-lc[0])/lr*r:r*Math.cos(angle)))*blend,origin[1]*(1-blend)+(cy+(local?-(local[k][1]-lc[1])/lr*r:r*Math.sin(angle)))*blend,origin[2]]});polys.push({fi,points,z:project(center)[2],cx,cy,number:j+1,sides:face.length})})});
polys.sort((a,b)=>a.z-b.z).forEach(poly=>{ctx.beginPath();poly.points.forEach((pt,k)=>k?ctx.lineTo(pt[0],pt[1]):ctx.moveTo(pt[0],pt[1]));ctx.closePath();ctx.fillStyle=poly.fi<amount?faceColor(poly.sides):(darkTheme?'#344862':'#edf1f7');ctx.fill();ctx.strokeStyle=(darkTheme?'#b1c5e0':'#405e87');ctx.lineWidth=1.4;ctx.stroke();if(blend>.85){ctx.globalAlpha=(blend-.85)/.15;ctx.fillStyle='#142c50';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(poly.number,poly.cx,poly.cy);ctx.globalAlpha=1}});
if(blend>.8){ctx.globalAlpha=(blend-.8)/.2;ctx.fillStyle=(darkTheme?'#e1e9f5':'#18283f');ctx.font='bold 16px sans-serif';ctx.textAlign='left';ctx.textBaseline='top';layouts.forEach(({g,y})=>ctx.fillText(g.name+'  '+g.ids.length+'枚',18,y));ctx.globalAlpha=1}}

function syncFullscreen(){const active=!!document.fullscreenElement||document.body.classList.contains('screen-expanded');$('fullscreen').textContent=active?'全画面表示 OFF':'全画面表示 ON';$('fullscreen').setAttribute('aria-pressed',active);requestAnimationFrame(draw)}
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement){await document.exitFullscreen()}else if(document.body.classList.contains('screen-expanded')){document.body.classList.remove('screen-expanded');$('fullscreenStatus').textContent=''}else if(document.documentElement.requestFullscreen&&document.fullscreenEnabled){await document.documentElement.requestFullscreen();$('fullscreenStatus').textContent=''}else{document.body.classList.add('screen-expanded');$('fullscreenStatus').textContent='画面内で最大表示中。ブラウザ全体はF11で切替。'}}catch{document.body.classList.add('screen-expanded');$('fullscreenStatus').textContent='画面内で最大表示中。ブラウザ全体はF11で切替。'}syncFullscreen()};document.addEventListener('fullscreenchange',syncFullscreen);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('screen-expanded')){document.body.classList.remove('screen-expanded');$('fullscreenStatus').textContent='';syncFullscreen()}});

function syncBuildGuide(){const c=cutConfigs[selected],guide=$('buildGuide');guide.hidden=!c;if(!c)return;const source=models[c.source];const depth=cutProgress*c.t,touch=Math.abs(depth-.5)<1e-7;$('cutDepth').value=Number((depth*200).toFixed(2));$('cutLabel').textContent=cutProgress===0?'元の立体':touch?'切り口が接する位置（辺の真ん中）':cutProgress===1?'辺がそろう基準位置':'辺の端から'+(depth*100).toFixed(1)+'％';$('buildIntro').textContent=c.name+'の'+c.cutCount+'個の頂点から、'+({3:'三角すい',4:'四角すい',5:'五角すい'}[c.cap])+'を切り取るぞ。';$('buildSteps').innerHTML=[c.mark,'1つの頂点につながる'+c.cap+'本の辺の印を平らな切り口で結ぶ。頂点側を取り除くと、'+c.capName+'の切り口ができる。','すべての'+c.cutCount+'個の頂点を同じように切る。元の'+c.originalName+'は'+c.oldName+'になって残るぞ。','切り口の'+c.capName+c.cutCount+'枚と、元の面から残る'+c.oldName+c.oldCount+'枚で完成！'].map(s=>'<li>'+s+'</li>').join('');$('cutMessage').textContent=cutProgress===0?'青い'+c.originalName+source.f.length+'枚の'+c.name+'から始めるぞ。':cutProgress===1?c.capName+c.cutCount+'枚 ＋ '+c.oldName+c.oldCount+'枚 ＝ '+models[selected].f.length+'面。':c.tip;}
function setCut(progress){const c=cutConfigs[selected];if(!c)return;progress=Math.max(0,Math.min(.5/c.t,progress));netState=null;netAnimation=null;cutProgress=progress;separation=0;peelAnimation=null;mode=0;const source=models[c.source];cutModel=progress===1?null:progress===0?{...source,newFaces:new Set()}:truncateSource(source,progress*c.t,c.cap);amount=models[selected].f.length;update();syncBuildGuide();showCutStage();if(cutModel){const totals={};cutModel.f.forEach(f=>totals[f.length]=(totals[f.length]||0)+1);$('faceTotals').innerHTML=Object.entries(totals).map(([n,total])=>'<span>'+({3:'三角形',4:'正方形',5:'五角形',6:'六角形',8:'八角形',10:'十角形'}[n])+' '+total+'枚</span>').join('');$('peelStatus').textContent='今の形の面の数。面をはがす操作では完成形に切り替わるぞ。';$('counter').textContent='基準位置で確認';$('viewHint').textContent='青は元の面、オレンジは切り口。回して裏側も見てみよう。';$('legend').innerHTML='<span><i class="dot" style="background:#6495ed"></i>元の面</span><span><i class="dot" style="background:#f1aa44"></i>切り口</span>';}}
let pendingCut=null,cutFrame=null;
$('cutDepth').oninput=e=>{pendingCut={solid:selected,value:+e.target.value};if(cutFrame===null)cutFrame=requestAnimationFrame(()=>{cutFrame=null;const next=pendingCut;pendingCut=null;if(next&&next.solid===selected&&cutConfigs[selected])setCut(next.value/(200*cutConfigs[selected].t))})};
$('cutDepth').onchange=e=>{pendingCut=null;if(cutFrame!==null){cancelAnimationFrame(cutFrame);cutFrame=null}setCut(+e.target.value/(200*cutConfigs[selected].t))};$('cutStart').onclick=()=>setCut(0);$('cutMiddle').onclick=()=>setCut(.5);$('cutFinish').onclick=()=>setCut(1);$('cutTouch').onclick=()=>setCut(.5/cutConfigs[selected].t);syncBuildGuide();

function syncTheme(){document.documentElement.dataset.theme=darkTheme?'dark':'light';$('darkMode').textContent=darkTheme?'ダークモード OFF':'ダークモード ON';$('darkMode').setAttribute('aria-pressed',darkTheme);draw()}$('darkMode').onclick=()=>{darkTheme=!darkTheme;try{localStorage.setItem('solid-lab-theme',darkTheme?'dark':'light')}catch{}syncTheme()};syncTheme();

function netSupported(){return selected>=3&&selected<=8}
function netName(i){return selected===8?['AEF','ABE','ECF','ADF'][i]:'面'+(i+1)}
function resetNetForSelection(){netState=null;netAnimation=null;netRoot=0;netYaw=0;netPitch=0;if(selected===8){netState=1;separation=0;peelAnimation=null}syncNet()}
function syncNet(){if(!$('netPanel'))return;const supported=netSupported();$('netPanel').hidden=!supported;if(!supported)return;const active=netState!==null,custom=selected===8;$('netBase').innerHTML=models[selected].f.map((f,i)=>'<option value="'+i+'">'+netName(i)+'</option>').join('');$('netBase').value=netRoot;$('netFold').value=Math.round((1-(netState??1))*100);$('netFold').disabled=!active;$('netOpen').classList.toggle('active',active&&netState===1);$('netClose').disabled=!active;$('netPlay').disabled=!active;$('netNote').textContent=custom?'元の図の点線で折ると、B・C・Dが1つの頂点Oに重なる。正四面体ではなく、面の形が異なる三角すいだぞ。':'正しい展開図の一例だぞ。実線は切り離す辺、破線はつながった折り目。面の番号で、元の面を追いかけよう。';$('baseNote').textContent=custom?[
'底面AEFは二等辺三角形。頂点はO（B＝C＝D）になる。赤い破線は底面に垂直な高さだ。',
'底面ABEはBが直角の三角形。組み立てると底面はAOE、頂点はFになる。',
'底面ECFはCが直角の二等辺三角形。組み立てると底面はEOF、頂点はAになる。',
'底面ADFはDが直角の三角形。組み立てると底面はAOF、頂点はEになる。'
][netRoot]:'底面にする'+netName(netRoot)+'を固定して、ほかの面を折り上げるぞ。正多面体はどの面も同じ形だから、底面を替えても同じ形に組み立つ。';$('netStatus').textContent=active?(netState===1?'展開図：色の濃い面が選んだ底面':netState===0?'完成：選んだ底面を下にして組み立てたぞ':'組み立て中：'+Math.round((1-netState)*100)+'％'):'「展開図を見る」で、辺がつながったまま開くぞ。';$('netReference').hidden=!custom;
if(active){$('viewHint').textContent='底面は紫色。ドラッグで回転、つまみで折る途中も確かめられるぞ。';$('legend').innerHTML='<span><i class="dot" style="background:#b692fa"></i>選んだ底面：'+netName(netRoot)+'</span><span>破線＝折り目</span>';$('count').disabled=true;$('counter').textContent='展開図を表示中';$('ghost').disabled=true;$('rotate').disabled=true;cv.setAttribute('aria-label',data[selected].title+'の展開図と組み立て。底面'+netName(netRoot));}}
function enterNet(value){cutModel=null;cutProgress=1;separation=0;peelAnimation=null;mode=0;netAnimation=null;netState=value;netYaw=0;netPitch=0;update()}
function animateNet(target){if(netState===null)enterNet(1);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){netState=target;update();return}netAnimation={from:netState,to:target,start:performance.now()}}
function tickNet(t){if(!netAnimation)return;let p=Math.min(1,(t-netAnimation.start)/1500),ease=p*p*(3-2*p);netState=netAnimation.from+(netAnimation.to-netAnimation.from)*ease;if(p===1)netAnimation=null;syncNet();draw()}
function netPolygons(model,edges,root,u){const polygons=NetEngine.unfold(model,edges,root,u);if(selected!==8)return polygons;
// Align every flat version with the supplied A-B-C-D square, regardless of the fixed face.
const flat=NetEngine.unfold(model,edges,root,1),ids=model.f[0],A=flat[0][ids.indexOf(0)],E=flat[0][ids.indexOf(1)],F=flat[0][ids.indexOf(2)],dx=E[0]-A[0],dy=E[1]-A[1],den=dx*dx+dy*dy,tx=.5,ty=-1;
const orientation=(dx*(F[1]-A[1])-dy*(F[0]-A[0]))>0?1:-1;
return polygons.map(face=>face.map(p=>{let x=p[0]-A[0],y=p[1]-A[1],along=(x*dx+y*dy)/den,across=orientation*(dx*y-dy*x)/den;return[tx*along-ty*across,1+ty*along+tx*across,p[2]]}));}
function drawNet(w,h){const m=models[selected],edges=netTrees[selected],polys=netPolygons(m,edges,netRoot,netState),tilt=(1-netState)*.88+netPitch,angle=netYaw;
const rotate=p=>{let [x,y,z]=p;[x,y]=[x*Math.cos(angle)-y*Math.sin(angle),x*Math.sin(angle)+y*Math.cos(angle)];return[x,y*Math.cos(tilt)+z*Math.sin(tilt),-y*Math.sin(tilt)+z*Math.cos(tilt)]};
const camera=polys.map(poly=>poly.map(rotate)),all=camera.flat(),xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min((w-80)/Math.max(.1,maxX-minX),(h-76)/Math.max(.1,maxY-minY)),cx=(minX+maxX)/2,cy=(minY+maxY)/2;
const projected=camera.map(poly=>poly.map(p=>[(p[0]-cx)*scale+w/2,-(p[1]-cy)*scale+h/2,p[2]])),hinges=new Set();edges.forEach(([a,b])=>{const shared=m.f[a].filter(id=>m.f[b].includes(id));hinges.add(shared.slice().sort((a,b)=>a-b).join(','))});
// Fill back faces too: a paper net has two visible sides.
const order=projected.map((p,i)=>({i,p,z:p.reduce((s,v)=>s+v[2],0)/p.length})).sort((a,b)=>a.z-b.z);const labelsToDraw=[];
order.forEach(({i,p})=>{ctx.beginPath();p.forEach((v,k)=>k?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fillStyle=i===netRoot?'#b692fa':selected===8?['#87b0f7','#f6c777','#83d6bf','#f1a8bc'][i]:'#82abea';ctx.fill();p.forEach((v,k)=>{const next=p[(k+1)%p.length],a=m.f[i][k],b=m.f[i][(k+1)%p.length],hinge=hinges.has([a,b].sort((a,b)=>a-b).join(','));ctx.beginPath();ctx.moveTo(v[0],v[1]);ctx.lineTo(next[0],next[1]);ctx.setLineDash(hinge&&netState>.01?[5,5]:[]);ctx.lineWidth=i===netRoot?2.5:1.5;ctx.strokeStyle=darkTheme?'#d2e2ff':'#354f76';ctx.stroke()});ctx.setLineDash([]);
const px=p.reduce((s,v)=>s+v[0],0)/p.length,py=p.reduce((s,v)=>s+v[1],0)/p.length;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold '+(selected===8?17:14)+'px sans-serif';ctx.fillStyle='#132b4c';ctx.fillText(netName(i)+(i===netRoot?'（底面）':''),px,py);
if(selected===8)p.forEach((pt,k)=>{const id=m.f[i][k],label=id===3?(netState<.01?'O':['','B','C','D'][i]):['A','E','F'][id];labelsToDraw.push({x:pt[0],y:pt[1],label})});});
if(selected===8&&netState<.001){const project=p=>{const q=rotate(p);return[(q[0]-cx)*scale+w/2,-(q[1]-cy)*scale+h/2]};const base=projected[netRoot];ctx.beginPath();base.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.strokeStyle=darkTheme?'#d9bfff':'#703db8';ctx.setLineDash([7,5]);ctx.lineWidth=3;ctx.stroke();ctx.setLineDash([]);const apexId=[3,2,0,1][netRoot],fi=m.f.findIndex(f=>f.includes(apexId)),apex=polys[fi][m.f[fi].indexOf(apexId)],foot=[apex[0],apex[1],0],a=project(apex),b=project(foot);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.strokeStyle=darkTheme?'#ffb0a3':'#bf4535';ctx.setLineDash([3,4]);ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);ctx.font='bold 14px sans-serif';ctx.fillStyle=darkTheme?'#ffcabf':'#a83228';ctx.fillText('高さ',(a[0]+b[0])/2+18,(a[1]+b[1])/2);}
if(selected===8){const used=[];labelsToDraw.forEach(p=>{if(used.some(q=>q.label===p.label&&Math.hypot(p.x-q.x,p.y-q.y)<8))return;used.push(p);ctx.fillStyle=darkTheme?'#f2f6ff':'#152c4e';ctx.strokeStyle=darkTheme?'#19263a':'white';ctx.lineWidth=4;ctx.font='bold 19px sans-serif';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.strokeText(p.label,p.x,p.y-6);ctx.fillText(p.label,p.x,p.y-6)});}}
function initNet(){ $('netOpen').onclick=()=>enterNet(1);$('netClose').onclick=()=>{netState=null;netAnimation=null;update()};$('netPlay').onclick=()=>animateNet(0);$('netUnfold').onclick=()=>animateNet(1);$('netFold').oninput=e=>{netAnimation=null;netState=1-(+e.target.value/100);update()};$('netBase').onchange=e=>{netRoot=+e.target.value;netAnimation=null;if(netState===null)netState=1;update()};resetNetForSelection();update();}

initNet();

function showCutStage(){const c=cutConfigs[selected],m=cutModel||models[selected],touch=Math.abs(cutProgress*c.t-.5)<1e-7;if(cutModel){$('summary').innerHTML=[m.f.length,m.e.length,m.v.length].map((n,i)=>'<div class="stat"><span>今の'+labels[i]+'</span><strong>'+n+'</strong></div>').join('');$('summary').setAttribute('aria-label','今の形の面・辺・頂点の数');$('summary').title='今の形の数';$('euler').textContent='今の形：頂点 '+m.v.length+' − 辺 '+m.e.length+' ＋ 面 '+m.f.length+' ＝ 2';$('stepLabel').textContent='下の式は、辺がそろう基準位置の説明';}
if(touch){const counts={};m.f.forEach((f,i)=>{const key=(cutModel?m.newFaces?.has(i):f.length===c.cap)?'切り口の'+c.capName:'残った'+c.originalName;counts[key]=(counts[key]||0)+1});$('cutMessage').textContent='切り口どうしが元の辺の真ん中で接したぞ。'+Object.entries(counts).map(([s,n])=>s+n+'枚').join('、')+'。これより先には進まない。';}else if(cutProgress>1){$('cutMessage').textContent='基準位置より深く切っているぞ。青い面の短い辺が縮み、つまみの右端で切り口どうしが接する。';}}
